### ISSUE TITLE
Transaction control

### ISSUE THREAD

**Issue by ghost** [zx80/anodb#1]
Hi,

when using psycopg (and I think also sqlite) directly, we can control transaction scope by using the connection object. This remains true even when we use `aiosql`, because the connection object is "outside" the aiosql object. For example:

```
conn = psycopg.connect("service=foo", autocommit=True)
queries = aiosql.from_path("queries.sql")
with conn.transaction():
    queries.insert_foo(conn, foo="foo")
    queries.insert_bar(conn, bar="bar")
crunch_numbers_furiously_for_hours()
with conn.transaction():
    queries.insert_baz(conn, baz="baz")

```

But with `anodb`, as it is now, I have to rely on peeking inside your object and (ab)using the ostensibly private `_conn` member. So you should consider one of:
 
1. Expose the `_conn` member, maybe just with a getter method, or
2. Make your own transaction interface, maybe by forwarding some methods calls automatically to `_conn`

Thanks for your attention,

-- 
Ian

**Comment by zx80** [comment]
The `commit`, `rollback`, `cursor` and `close` methods are already forwarded to the `_conn` object.

I understand that you want to forward `transaction` as well, which is not part of PEP249, so I'm not sure I want that because it would work with `psycopg 3` but not with `psycopg 2`, unless it is re-implemented.

I'm fine with adding a getter on `_conn`.

I'll think about exposing `transaction`, but I'm not convinced that it should go this way.

**Comment by zx80** [comment]
This is implemented in 3499255916009ee118851969618c2d80101ff4cf by making `connect()` return the current connection.

After some thinking, I do not think that the non standard methods should be exposed.

**Comment by ghost** [comment]
Not arguing with your decision, I suspect mine would be the same.

I am curious, though, what was the logic in the PEPs to standardize `commit` and `rollback` but not `transaction`? That doesn't seem to make sense.

-- 
Ian

**Comment by zx80** [comment]
> I am curious, though, what was the logic in the PEPs to standardize `commit` and `rollback` but not `transaction`? That doesn't seem to make sense.

I guess that when they wrote PEP249 there was no `with` statement in Python :smiley:
