### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by UberKitten** [zx80/anodb#4]
Thank you for your time on this package, it's a really elegant way to interface with aiosql.

I'm stuck on Python 3.9 for the moment because one of my libraries isn't compatible with 3.10+ (appdynamics). Would it be possible to bring back 3.9 support? Probably would mean having to use the old union type syntax, sorry.

I saw this comment mentioning 3.7 and 3.8 weren't compatible:
https://github.com/zx80/anodb/blob/8743f64f66538e9fac038e4c622f353a29ec5eb7/.github/workflows/anodb-package.yml#L15

**Comment by zx80** [comment]
Please simply install an older version which supports the version you want, for instance:

```shell
pip install anodb==7.3
```
